version: "3.1"
services:
  postgres:
    image: postgres:11.1-alpine
    restart: always
    volumes:
     - .:/data
  api:
    build: ./
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - .:/usr/local/api
    environment:
      - DB_HOST=postgres
      - DB_NAME=postgres
      - DB_USER=postgres
